### ISSUE TITLE
script execution errors on linux

### ISSUE THREAD

**Issue by masbug** [srinivasupadhya/script-executor-task#4]
Hello,

I found a bug in this plugin... on linux the script is written with "\r\n" line endings (which is correct on windows) and it results in execution errors such as:
```
[script-executor] OS detected: 'Linux'. Is Windows? false
[script-executor] Script written into '/media/ext/go-agent/pipelines/test/f1455bb2-7fe1-45b6-9fee-3b5528fe0750.sh'.
./f1455bb2-7fe1-45b6-9fee-3b5528fe0750.sh: line 1: $'env\r': command not found
```
Because "sh" doesn't handle \r and adds them to the executed command.

Best regards,
Mitja

**Comment by srinivasupadhya** [comment]
Yes. This is due to this issue in Go - https://github.com/gocd/gocd/issues/815.
Should i strip `\r` before writing the script into the file?

**Comment by masbug** [comment]
Hmm, I guess those line endings are sent by the browser and depend on the user's system. If that's the case I think the code should look something like this:
```
scriptValue.replaceAll("(\\r\\n|\\n|\\r)", System.getProperty("line.separator"));
```
I believe this should handle all situations.

**Comment by srinivasupadhya** [comment]
This is fixed now. Thanks @masbug and @voitau.
