### ISSUE TITLE
Doesn't seem to allow scripts that span more than one line

### ISSUE THREAD

**Issue by jefftrimm** [srinivasupadhya/script-executor-task#6]
We've noticed that the script executor task doesn't like scripts that span more than one line.  Is this intentional???

**Comment by srinivasupadhya** [comment]
shouldn't be the case. could be due to #4 fix. can you cat the script & post the output?

**Comment by jefftrimm** [comment]
Ah... the plugin version we are using is from a month ago.  Looks like fix for #4 is the issue we are seeing.  We'll try latest.  Thanks!

**Comment by jefftrimm** [comment]
Quick question:  if I replace /var/lib/go-server/plugins/external/script-executor-0.1.jar with /var/lib/go-server/plugins/external/script-executor-0.2.jar

what happens to the  script-executor-0.1.jar in my 50 or so agent directories?  ie: /var/lib/go-agent/plugins/external/script-executor-0.1.jar

Is Go smart enough to blow away all previous jars and refresh them with the plugins in /var/lib/go-server/plugins/external/  or will I end up with both script-executor-0.1.jar and script-executor-0.2.jar in the /var/lib/go-agent/plugins/external/ directory of all my agents?

**Comment by jefftrimm** [comment]
We're good to go: script-executor-0.2.jar fixed our problems.  Also, we answered my last question by holding our breath and replacing the jar in the go-server directory (hoping we wouldn't have to go clean up 50+ agent installs).  Go upgraded the plugins in all of the agents cleanly... looks like it does so even if the agents are explicitly run.  Very nice!

**Comment by srinivasupadhya** [comment]
great! :) & yes Go takes care of upgrading plugins on all agents. Agents automatically restart after plugin upgrade as well.
