### ISSUE TITLE
Script executor fails to save when hash character part of command

### ISSUE THREAD

**Issue by kojiromike** [srinivasupadhya/script-executor-task#7]
If I have a script like

```sh
curl -#O http://example.com
```

The script executor will fail to save. If I remove the `#`, the script executor will save without issue. Single-quoting the expression (`curl '-#O' …`) does not help. The expression itself is a valid shell command.

**Comment by arvindsv** [comment]
Probably related to [this](https://github.com/gocd/gocd/issues/817).

**Comment by kojiromike** [comment]
@arvindsv yeah, seems to fail when any hash character occurs anywhere in the script.

**Comment by srinivasupadhya** [comment]
This is a fix on Go's side.

**Comment by pracplayopen** [comment]
this is a feature, not a bug.  reason is gocd uses #{gocd-var-name} to designate a gocd-supplied script.

work-around is put two hashes together:
```
uname -a
## hello world --> gocd treats this as '# hello world'
uptime
```

this passes gocd script-checker and also outputs/runs as we would expect in the shell.
